メモアプリを作成
maaaru09/memo-app pull request #1
Opened 2024-02-11 05:42 UTC by maaaru09

ご確認宜しくお願いします。

2024-02-17 11:32 UTC, u1tnk commented
差分のファイルが大き過ぎて、FileChangedページが重すぎるのでこちらに書きます。重過ぎて見れないのでまだ以下の内容以外は見れてないです 🙏 
- Gemfile.lock の内容がGemfileと違うようです。(rails用のgemなどが入っています)Gemfileを作ってから `bundle install`されましたか？ `Gemfile.lock` はそのときに自動で作られます。
- 差分が大きいのは`vendor/bundle` に gemのプログラム本体がコミットされてしまっていることが原因なのですが、 `.bundle/config` を見ると`bundle install --path vendor/bundle` ってされたんじゃないかと思います。昔は定番だったので、よく手順など調べたら出ると思うんですが、 今は特に `--path` を付ける必要が無いです。また付けても良いんですが、 その場合は `vendor/bundle` を `.gitignore` の対象にしてコミットしないようにすると良いですね。

2024-02-17 15:29 UTC, maaaru09 commented
`.gitignore`を作成して、余分なファイルをコミットしないようにしました！
丁寧に方法まで教えて下さって、ありがとうございます🙇

改めてご確認宜しくお願いいたします！

2024-02-18 16:09 UTC, u1tnk requested changes
> Gemfile.lock の内容がGemfileと違うようです。(rails用のgemなどが入っています)Gemfileを作ってから bundle installされましたか？ Gemfile.lock はそのときに自動で作られます。

これは前回の指摘ですが、返答など無かったのですが確認されましたでしょうか？

複数指摘されたとき、一番気になっていた部分以外すっぱりと抜けるのが仕事でもよく見るし、僕もたまにやってしまうのですが、なるべく指摘されたこと全て返答を返すように気をつけましょう。

2024-02-18 16:09 UTC, u1tnk commented on memo.rb
> +MEMO_FILE = 'public/memos.json'
これは memos/memo_writeに定数で渡しているようですが、全て同じ引数であるなら memos/memo_write の中で参照すれば良いですね。

2024-02-18 16:09 UTC, u1tnk commented on memo.rb
> +def memo_write(memo_file, memos)
メモを読み込むのが `memos` であるのはおかしく無いですが、メモを書き込むのが `memo_write`と `memo`になっているのがおかしいです。 memo一件を書き込むメソッドのように見えます。
単数形と複数形はrubyというか特にrails関連では明確に区別しないと誤解を招きます。

また、 メソッド名は 基本`動詞`もしくは`動詞_目的語になる名詞` の順番が一般的です。
ちなみに変数を読み込むような処理はイディオムとして `名詞` となります。なので memosはおかしく無いです。

2024-02-18 16:09 UTC, u1tnk commented on memo.rb
> +get '/memos/?' do
この `/?` の部分必要ですか？

2024-02-18 16:09 UTC, u1tnk commented on views/show.erb
> +<% @memos.each do |key, memo| %>
`@memos` から表示するメモ情報を選択する処理は controllerにしましょう。
viewには必要最低限のデータを渡すようにしましょう。

2024-02-18 16:09 UTC, u1tnk commented on views/show.erb
> +      <% title = memo['title'] %>
tilte/contentは一回しか使わないから変数を作る必要は無いです。

2024-02-18 16:09 UTC, u1tnk commented on views/edit.erb
> +<% @memos.each do |key, memo| %>
showと同じです。

2024-02-19 04:03 UTC, maaaru09 commented on memo.rb
> +get '/memos/?' do
仰る通り不要だったので削除しました！

2024-02-19 05:18 UTC, maaaru09 commented on memo.rb
> +def memo_write(memo_file, memos)
頂いたご意見を参考にメソッド名を変更しました！

2024-02-19 05:47 UTC, maaaru09 commented
レビューありがとうございます！

以下を修正しました。
- `MEMO_FILE`という定数を削除
- `get '/memos/?'`の`/?`を削除
- `memo_id = params[:memo_id]`も不要な変数だと感じたので削除
- `memo_write`というメソッド名が不適切なので`write_memos`に変更
  - 英語的に大丈夫でしょうか？ 
- viewで記述していた処理をコントローラに移動
- `show_memos`というメソッドを作成
  -  詳細ページと編集ページで取得する内容が同一だったため。

---

また、`Gemfile.lock`についてですが、仰る通り大きな指摘に気を取られて失念しておりました。以後気を付けます！

`bundle install --path vendor/bundle` をしてから、`Gemfile`に追記して、再び`bundle install --path vendor/bundle` したかもしれません(記憶が曖昧で申し訳ありません)。

`Gemfile`と`Gemfile.lock`の中身の差異を解決しようと思い以下の記事を参考に実行したのですが、`Gemfile.lock`の中身は特に変化がないようです。
[途中から--path-vendorbundleからデフォルトに切り替えたいときはどうすればいい？](https://qiita.com/jnchito/items/99b1dbea1767a5095d85#202224%E8%BF%BD%E8%A8%98%E9%80%94%E4%B8%AD%E3%81%8B%E3%82%89--path-vendorbundle%E3%81%8B%E3%82%89%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%AB%E5%88%87%E3%82%8A%E6%9B%BF%E3%81%88%E3%81%9F%E3%81%84%E3%81%A8%E3%81%8D%E3%81%AF%E3%81%A9%E3%81%86%E3%81%99%E3%82%8C%E3%81%B0%E3%81%84%E3%81%84)

何かアドバイス頂けると幸いです。
よろしくお願いします！

2024-02-19 14:51 UTC, u1tnk requested changes
Gemfile.lockのrails用のgem群は確認したところ `erb_lint` が必要としているから入っているようですので問題ありませんでした 🙏

2024-02-19 14:51 UTC, u1tnk commented on Gemfile
> +gem "sinatra", "~> 4.0"
修正不要ですが、バージョン固定する必要の無いものはバージョン指定しなくて良いです。
`bundle update`などで`Gemfile.lock`の方を更新しない限りバージョンは固定されます。

2024-02-19 14:51 UTC, u1tnk commented on memo.rb
> +def show_memos
こういう共通メソッドでインスタンス変数を設定するのはおすすめしないです。どこで設定されているか分からなくなるので。
(railsなどでイディオム化しているものは一部ありますが)

また、 `@memos` はここで設定する必要ありますでしょうか？ 
viesで参照してなくてもインスタンス変数に入れると参照できます。
プログラムでは「参照できる」ということは便利そうでいて、どこから見ているか？どこから変更されるか分からないことに繋がるので逆に必要無ければ見えない方が良いんです。

また、 id/title/contentとばらばらに渡していますが、 `@memo` 一つで渡した方がひとまとまりの情報と明確になるし手間も減ると思います。

2024-02-20 04:14 UTC, maaaru09 commented
レビューありがとうございます！

- `show_memos`メソッドを変更しました
  -   `@memos`の削除
  -  `title`と`content`を`@memo`にまとめてviewsでそれぞれ`@memo['title']`と`@memo['content']`と記述して展開するようにしました。 

idだけ上手くまとめられなかったのですが、
```ruby
def show_memos
  @memo = memos[params[:memo_id]]
end
```
とした方が良いのでしょうか？
viewsで呼び出す際にうまくいかず現在の形で提出しました。

ご確認よろしくお願いします！

2024-02-20 15:16 UTC, u1tnk approved these changes
OKです 🙆‍♀️ 

`@memo_id` は titleとcontentと同様に入れても良いですが、それはそれで重複するし、どっちでも良いかと思います。

今さら見逃していたのですが `<br />` を使っていることについてはcssの課題では無いので問題ありません。

2024-02-21 14:13 UTC, merged