SinatraメモアプリのDB版です
maaaru09/memo-app pull request #2
Opened 2024-03-04 10:47 UTC by maaaru09

ご確認よろしくお願いします！

2024-03-04 15:58 UTC, u1tnk requested changes

2024-03-04 15:58 UTC, u1tnk commented on memo.rb
> +  max_id = connect_db.exec('SELECT MAX(id) FROM memos').getvalue(0, 0).to_i
max_idは必要無いですね。 id以外を指定してinsertすれば自動採番されます。

2024-03-04 15:58 UTC, u1tnk commented on memo.rb
> +def connect_db
> DB接続は遅い(重い)処理なので使い回せるようにしよう。

とプラクティスに指定していますので対応してください。

2024-03-04 15:58 UTC, u1tnk commented on memo.rb
> +  params[:memo_id].to_i
修正するほどでは無いですが、 paramsから取得するような処理を共通化すると、これはどこから取得したんだ？と迷うことになりがちなのであまり良くないですね。

2024-03-04 15:58 UTC, u1tnk commented on memo.rb
>  def show_memos
こちら前回指摘漏れたと思いますが、 show_memosだと複数返って来そうなので単数と分かるようにしましょう。

また、前回はスルーしたかもしれませんが、共通化してインスタンス変数に入れるのはどこで入れてるのか分からなくなりがちなのと、単にデータが欲しいときに不便なので、データを取得するだけのメソッドにして、インスタンス変数にはcontrollerで入れるようにしましょう。

2024-03-05 08:51 UTC, maaaru09 commented on memo.rb
> +  params[:memo_id].to_i
念の為、修正しました！

2024-03-05 10:11 UTC, maaaru09 commented
レビューありがとうございます。
主な変更は`connect_db`メソッドを定数`CONNECT_DB`にしたことです。
他にもご指摘いただいた箇所の修正及び、以下の点も一応変更しました🙇

>修正するほどでは無いですが、 paramsから取得するような処理を共通化すると、これはどこから取得したんだ？と迷うことになりがちなのであまり良くないですね。

ご確認よろしくお願いします！

2024-03-05 11:17 UTC, u1tnk requested changes
一箇所お願いします！
あと、前回説明が足りなかったですが、 max_idのところですが、仮にこれがwebサービスとして配置してあるとすると、DB一つにwebサーバが複数あるのが普通なので、ほぼ同時にアクセスされるとidが同じになって片方がエラーになっちゃいます。
DB側に保存と同時に採番されるとDB側で排他制御されるので大丈夫です。DBはこういうところでも便利なんです。

2024-03-05 11:17 UTC, u1tnk commented on memo.rb
> +CONNECT_DB = PG.connect(dbname: 'my_memo')
動作は良いのですが、定数に状態の変わるインスタンスを入れるのは慣習的にNGです！
別のものにしましょう。
また、connect_dbという名前だと毎回接続を実行することを期待してしまうのでこういう実装の場合は名詞にした方が良いでしょう。

2024-03-06 13:12 UTC, maaaru09 commented
レビューありがとうございます！

`my_memo`はこのアプリケーション上において変化させる予定がないので`DB_NAME`という定数にしてみました。
これでは解決できていないでしょうか？

`CONNECT_DB`の名前はシンプルに`DB`としてみました。

ご確認よろしくお願いします！

2024-03-07 15:38 UTC, u1tnk requested changes

2024-03-07 15:38 UTC, u1tnk commented on memo.rb
> +DB = PG.connect(dbname: DB_NAME)
名前は良いのですが、前も書きましたが定数に接続を入れるのはやめましょう。
定数は絶対に状態の変わらないものだけにしましょう。

2024-03-08 09:34 UTC, maaaru09 commented
レビューありがとうございます。
同じ間違いをしてしまい申し訳ないです。

今回は`configure`ブロックの中で`set`を使用し、CRUD操作の際に`settings.db`で呼び出すようにしています。

ご確認よろしくお願いします！

2024-03-08 14:39 UTC, u1tnk approved these changes

2024-03-08 14:50 UTC, u1tnk commented
> 1点質問です！
configureはあってもなくても接続の再利用はできているのですが、アプリケーション起動時にブロックの中身を1回だけ実行してくれるという特性があると知り、役割を明らかにする目的で使ってみました。今回の場合は不要でしょうか？

sinatraあんまり詳しく無いのですが、

https://sinatrarb.com/intro.html

を見ると configureは一回だけ実行する特性以外にもdevelopmentやtestだけで実行したりと色々機能があるみたいですね。
今回で言うと特に使う必要は機能的には無いですが、設定をしているところを明確化するという点では良いと思います。

2024-03-09 06:39 UTC, merged